baseURL = 'https://blinkofai.io/'
languageCode = 'en-us'
title = 'BlinkofAI'

[params]
  description = 'BlinkofAI - AI-powered solutions'

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "blog/"
    weight = 1
  [[menu.main]]
    identifier = "case-studies"
    name = "Case Studies"
    url = "case-studies/"
    weight = 2
  [[menu.main]]
    identifier = "pricing"
    name = "Pricing"
    url = "pricing/"
    weight = 3

