baseURL = 'https://karpe29.github.io/boai-website/'
languageCode = 'en-us'
title = 'BlinkofAI'
theme = ''

[params]
  description = 'BlinkofAI - AI-powered solutions'

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 1
  [[menu.main]]
    identifier = "pricing"
    name = "Pricing"
    url = "/pricing/"
    weight = 2

